name: release
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: default
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ARTIFACT_REGISTRY_USER: ${{ secrets.ARTIFACT_REGISTRY_USER }}
      ARTIFACT_REGISTRY_PASSWORD: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
      GPG_PASSPHRASE: $${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: $${{ secrets.GPG_PRIVATE_KEY }}
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: make run-test
      - run: make build-package
      - run: find  ${{github.workspace }} -type f -iname "*sonar-clover-plugin.jar*"
      #- run: make quality-analysis
      #- run: make deploy-package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: clover jar publish
          path: /usr/src/target/sonar-clover-plugin.jar*"
        if: ${{ always() }}  
    
